### ISSUE TITLE
宠汪汪脚本失效

### ISSUE THREAD

**Issue by huamu88** [lan-tianxiang/jd_shell#105]
3天前活动脚本就失效了
您设置的喂食数量:80g

实际的喂食数量:80g

其他状态success

❗️宠汪汪, 错误!
TypeError: $.getPetTaskConfigRes.datas is not iterable
    at petTask (/data/data/com.termux/files/home/jd/scripts/jd_joy.js:230:42)
    at jdJoy (/data/data/com.termux/files/home/jd/scripts/jd_joy.js:111:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /data/data/com.termux/files/home/jd/scripts/jd_joy.js:83:7

**Comment by huamu88** [comment]
是最新的代码

**Comment by lan-tianxiang** [comment]
已修复，请更新

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："huamu88 ***@***.***&gt;;
发送时间：2021年6月5日(星期六) 晚上11:06
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 宠汪汪脚本失效 (#105)
-----------------------------------

 

 
3天前活动脚本就失效了
 您设置的喂食数量:80g
 
实际的喂食数量:80g
 
其他状态success
 
️宠汪汪, 错误!
 TypeError: $.getPetTaskConfigRes.datas is not iterable
 at petTask (/data/data/com.termux/files/home/jd/scripts/jd_joy.js:230:42)
 at jdJoy (/data/data/com.termux/files/home/jd/scripts/jd_joy.js:111:9)
 at processTicksAndRejections (internal/process/task_queues.js:97:5)
 at async /data/data/com.termux/files/home/jd/scripts/jd_joy.js:83:7
