### ISSUE TITLE
关于脚本自动运行的问题

### ISSUE THREAD

**Issue by kotonamihuiren** [lan-tianxiang/jd_shell#109]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [x ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：如何让脚本自动化运行 每次都要手动输入bash run_all.sh 然后脚本都跑一遍进入joy收金币然后不会自动定时重新跑脚本 重启挂机脚本是joy收金币

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
什么系统，centos还是安卓什么的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："kotonamihuiren ***@***.***&gt;;
发送时间：2021年6月7日(星期一) 上午8:50
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 关于脚本自动运行的问题 (#109)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
[x ] Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
[x ] Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
[x ] Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：如何让脚本自动化运行 每次都要手动输入bash run_all.sh 然后脚本都跑一遍进入joy收金币然后不会自动定时重新跑脚本 重启挂机脚本是joy收金币
 
(2) 详细日志
 
A：

**Comment by kotonamihuiren** [comment]
win10下载的Ubuntu。  脚本内显示操作系统debian

**Comment by lan-tianxiang** [comment]
有输入 特别提醒的代码吗

**Comment by lan-tianxiang** [comment]
`service cron start`

**Comment by kotonamihuiren** [comment]
没有 我去试试

**Comment by kotonamihuiren** [comment]
Starting periodic command scheduler cron ［Ok］ 提示这个

**Comment by kotonamihuiren** [comment]
好像可以了再用用看看

**Comment by qingcheng123** [comment]
手动运行是bash run_all.sh吗

**Comment by lan-tianxiang** [comment]
@qingcheng123   输入`bash jd.sh` 会有帮助提示

**Comment by lan-tianxiang** [comment]
> 手动运行是bash run_all.sh吗

bash run_all.sh是运行全部任务

**Comment by qingcheng123** [comment]
我按照里面提示单个运行，都会出现一些莫名其妙的错误，centos环境下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月8日(星期二) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lan-tianxiang/jd_shell] 关于脚本自动运行的问题 (#109)

**Comment by qingcheng123** [comment]
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/jd/jd_zoo,js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by lan-tianxiang** [comment]
> 我按照里面提示单个运行，都会出现一些莫名其妙的错误，centos环境下------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年6月8日(星期二) 下午5:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [lan-tianxiang/jd_shell] 关于脚本自动运行的问题 (#109)

好的，是个问题，等等修复，现在主要更新A1版本
