### ISSUE TITLE
有哪些脚本失效在这边反馈

### ISSUE THREAD

**Issue by lan-tianxiang** [lan-tianxiang/jd_shell#137]
欢迎提供可用的替代脚本

**Comment by lan-tianxiang** [comment]
2021.06.14 10:00AM  jd_zoo&jd_zooCollect暂时失效

**Comment by Egnus-s** [comment]
jd_beauty&jd_live_redrain

**Comment by CT0217** [comment]
jd_jxlhb.js

**Comment by lan-tianxiang** [comment]
@Egnus-s  jd_beauty&jd_live_redrain 已确认失效

**Comment by lan-tianxiang** [comment]
jd_jxlhb.js没问题

**Comment by CT0217** [comment]
好的，我把的jxlhb进入助力后死循环了，我去重新安装一下

**Comment by SNAKEXGC** [comment]
jd_plantBean.js失效了api请求不到

**Comment by CT0217** [comment]
![8aacb171aec3f298d6553a403fcd886](https://user-images.githubusercontent.com/77103305/122032565-58342180-ce02-11eb-9601-8270da45de48.jpg)
老大，惊喜88一直卡在这里，/(ㄒoㄒ)/~~，如何解，跳不过去/(ㄒoㄒ)/~~

**Comment by lan-tianxiang** [comment]
好的，我今晚把助力作者那块删了@CT0217

**Comment by benkyocn** [comment]
jxmc一直出错

**Comment by 2767321434** [comment]
jd_joy_reward 失效了 
脚本开始请求时间 2021-06-21 08:00:02 | 635
当前积分 undefined

宠物等级 undefined


debug场次:beanConfigs8


❗️宠汪汪积分兑换奖品, 错误!
TypeError: data[giftSaleInfos] is not iterable
    at joyReward (/root/jd/scripts/jd_joy_reward.js:139:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /root/jd/scripts/jd_joy_reward.js:88:9

**Comment by ryan868** [comment]
jxmc

**Comment by timessage** [comment]
大佬，那个扫码登录的，扫完码没有获取ck直接显示二维失效，

**Comment by Rosylusi** [comment]
> 大佬，那个扫码登录的，扫完码没有获取ck直接显示二维失效，

同，不知道是不是挂了

**Comment by 13758120317** [comment]
京东多合一签到报错jd_dailybonus.js文件不存在

**Comment by 13758120317** [comment]
crazyJoy脚本不生效，无法获取京豆和joy信息
