### ISSUE TITLE

jd.sh: line 262:  2553 Killed                  nohup node ${PanelDir}/server.js > /dev/null 2>&1
确认看过WIKI，打开浏览器，地址为你的127.0.0.1:5678
打不开面板。

### ISSUE THREAD

**Issue by 442774765** [lan-tianxiang/jd_shell#141]

**Comment by lan-tianxiang** [comment]
哪个版本的

**Comment by lan-tianxiang** [comment]
A1还是jdshell

**Comment by 442774765** [comment]
v3

**Comment by lan-tianxiang** [comment]
你输入
```
cd jd/panel
node server.js
```

**Comment by 442774765** [comment]
[HPM] Proxy created: /  -> http://localhost:9999
[HPM] Proxy rewrite rule created: "^/shell" ~> "/"
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5678
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/root/jd/panel/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/root/jd/panel/server.js:811:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[root@SXHostIP2 panel]# node server.js
[HPM] Proxy created: /  -> http://localhost:9999
[HPM] Proxy rewrite rule created: "^/shell" ~> "/"
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5678
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/root/jd/panel/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/root/jd/panel/server.js:811:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
You have new mail in /var/spool/mail/root

**Comment by 442774765** [comment]
已经反复删除，安装a1 V3 docker面板都启动不成功。

**Comment by lan-tianxiang** [comment]
你的docker是安装到服务器上还是其他设备里面，服务器的话，我帮你部署

**Comment by lan-tianxiang** [comment]
> listen EADDRINUSE: address already in use

这个是端口占用了

**Comment by 442774765** [comment]
百度搜索查看一下，试用这些命令成功了。firewall-cmd --zone=public --add-port=5678/tcp --permanent   # 开放5678端口
firewall-cmd --zone=public --list-ports
firewall-cmd --reload   # 配置立即生效

**Comment by lan-tianxiang** [comment]
嗯，那是防火墙没开
