### ISSUE TITLE
无法开启面板

### ISSUE THREAD

**Issue by cuxevip** [lan-tianxiang/jd_shell#23]
[root@instance-8888-1 jd]# bash jd.sh panelinit
记得开启前先认真看Wiki中，功能页里关于控制面板的事项

/root/jd/panel/server.js:75
async function step1() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
开启失败，请截图并复制错误代码并提交Issues！

请问一下，这个要怎么解决？

**Comment by lan-tianxiang** [comment]
请按模板提交问题呀兄弟，什么系统？ 是不是用一键脚本安装的？  

试一下用修复脚本
 请看  #17 
和你很像
