### ISSUE TITLE
部署在服务器控制面板无法开启

### ISSUE THREAD

**Issue by WTH200** [lan-tianxiang/jd_shell#28]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：服务器端用Ubuntu加了docker的源部署控制面板提示开启失败

### (2) 详细日志
A：root@jd:~/jd $ bash jd.sh panelinit
记得开启前先认真看Wiki中，功能页里关于控制面板的事项

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5678
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.listen (/root/jd/panel/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/root/jd/panel/server.js:597:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 5678
}
开启失败，请截图并复制错误代码并提交Issues！

**Comment by lan-tianxiang** [comment]
Error: listen EADDRINUSE: address already in use :::5678

**Comment by lan-tianxiang** [comment]
你的端口被占用了

**Comment by lan-tianxiang** [comment]
编辑server.js，到最后一行，把5678更改为54321，一般就可以了
