### ISSUE TITLE
telegram发送通知消息失败！！

### ISSUE THREAD

**Issue by ryan016** [lan-tianxiang/jd_shell#44]
tg信息发送失败
TG_BOT_TOKEN 与 TG_USER_ID 确认填写无误

```


RequestError: Timeout awaiting 'request' for 10000ms
    at ClientRequest.<anonymous> (/jd/scripts/node_modules/got/dist/source/core/index.js:953:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/jd/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Timeout.timeoutHandler [as _onTimeout] (/jd/scripts/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:492:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1617357833781,
    socket: 1617357833784,
    lookup: 1617357833785,
    connect: 1617357833802,
    secureConnect: 1617357838223,
    upload: 1617357838225,
    response: undefined,
    end: undefined,
    error: 1617357843797,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 1,
      tcp: 17,
      tls: 4421,
      request: 2,
      firstByte: undefined,
      download: undefined,
      total: 10016
    }
  },
  event: 'request'
}
```

**Comment by lan-tianxiang** [comment]
好的，我今晚重点帮你看一下

**Comment by ryan016** [comment]
> 好的，我今晚重点帮你看一下

万分感谢！！！

**Comment by lan-tianxiang** [comment]
帮你分析了，仔细看了一下是超时的问题，我的这部分是正常的，你这个日记的出现应该TG收到消息了，目前这个脚本也是库的作者，你可以去问问，我的这部分没有问题。
从你的日记来看，你网络可以连接外网，但是速度太慢了

**Comment by ryan016** [comment]
> 帮你分析了，仔细看了一下是超时的问题，我的这部分是正常的，你这个日记的出现应该TG收到消息了，目前这个脚本也是库的作者，你可以去问问，我的这部分没有问题。
> 从你的日记来看，你网络可以连接外网，但是速度太慢了

好的，辛苦了！
