### ISSUE TITLE
开启shell报错

### ISSUE THREAD

**Issue by chinkaysin** [lan-tianxiang/jd_shell#88]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

[root@VM-0-6-centos jd]# bash jd.sh shellon
记得开启前先认真看Wiki中，功能页里关于Webshell的事项

/usr/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
        ...styles,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/constants.js:10:14)
开启失败，请截图并复制错误代码并提交Issues！

**Comment by lan-tianxiang** [comment]
这个问题我稍后更新

**Comment by qingcheng123** [comment]
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
您的操作系统为：Centos 架构：x86_64
