### ISSUE TITLE
Docker映射路径错误

### ISSUE THREAD

**Issue by RealKiro** [lan-tianxiang/jd_shell#91]
https://github.com/lan-tianxiang/jd_shell/blob/855a547e96d661a0bf814254813ca0fd6c4586c8/docker/docker-compose.yml#L11

- 日志：
![image](https://user-images.githubusercontent.com/33367701/120098145-d5a33500-c166-11eb-9fc4-9efcaa2a487d.png)

- 更正路径：
![image](https://user-images.githubusercontent.com/33367701/120098211-231fa200-c167-11eb-90d3-1d0a41785395.png)

**Comment by implanb** [comment]
我装载路径 /jd/config 但是在映射文件夹中看不到config文件和log 但是容器可以运行 不知道为什么

**Comment by lan-tianxiang** [comment]
好，手上暂时没有设备，测试不了😂&nbsp;

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："implanb ***@***.***&gt;;
发送时间：2021年5月30日(星期天) 下午5:11
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] Docker映射路径错误 (#91)
-----------------------------------

 

 
我装载路径 /jd/config 但是在映射文件夹中看不到config文件和log 但是容器可以运行 不知道为什么

**Comment by lan-tianxiang** [comment]
我尝试排除一下

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："implanb ***@***.***&gt;;
发送时间：2021年5月30日(星期天) 下午5:11
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] Docker映射路径错误 (#91)
-----------------------------------

 

 
我装载路径 /jd/config 但是在映射文件夹中看不到config文件和log 但是容器可以运行 不知道为什么

**Comment by qingcheng123** [comment]
请问这是什么错误呢
(node:3630) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `Resolver` of 'undefined' or 'null'.
    at Object.<anonymous> (/jd/scripts/node_modules/cacheable-lookup/source/index.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/jd/scripts/node_modules/got/dist/source/core/index.js:12:28)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
(node:3630) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 109)

**Comment by lan-tianxiang** [comment]
@qingcheng123   一般是node版本问题,百度搜索node版本升级。推荐安装docker后，用docker一键脚本
