### ISSUE TITLE
如何在服务器端打开浏览器访问面板

### ISSUE THREAD

**Issue by fyzdhy** [lan-tianxiang/jd_shell#96]

**Comment by lan-tianxiang** [comment]
部署方式是什么的

**Comment by fyzdhy** [comment]
Linux服务器，centos

**Comment by SoYeonQwQ** [comment]
以前部署的自动更新后面板打不开，需要使用bash repair.sh修复，修复后可打开面板。

**Comment by lan-tianxiang** [comment]
cd jd进入目录
bash jd.sh panelon打开面板
bash jd.sh有提示
推荐安装docker后，走docker路线
----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："fyzdhy ***@***.***&gt;;
发送时间：2021年5月31日(星期一) 晚上9:48
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/jd_shell] 如何在服务器端打开浏览器访问面板 (#96)
-----------------------------------

 

 
Linux服务器，centos

**Comment by fyzdhy** [comment]
浏览器面板进不去

**Comment by fyzdhy** [comment]
jd.sh: line 156: combine_sub: command not found
0000
/root/jd/scripts/jd_club_lottery.js:50
!(async () => {
        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by lan-tianxiang** [comment]
@fyzdhy  用bash repair.sh修复试试，昨天面板更新了

**Comment by lan-tianxiang** [comment]
JD_SHELL 这个是旧版，新版链接 https://github.com/lan-tianxiang/JS_TOOL
