### ISSUE TITLE
请问能否按账号分别进行通知呢

### ISSUE THREAD

**Issue by HarrisonQi** [lan-tianxiang/jd_shell#97]
### 想要增加什么样的功能或者哪里存在不足之处呢？

目前的通知是N个账号都通过一个渠道进行通知, 当账号多的时候, 大家会很难找到自己账号的信息.

能否添加功能, 使每个cookie对应自己的通知(拿钉钉通知举例), 如:

```js
# 账号1
Cookie1=xxxxx
# 钉钉通知
export DD_BOT_TOKEN_1="xxx"
export DD_BOT_SECRET_1="xxx"

# 账号二
Cookie2=xxxxx
# 钉钉通知
export DD_BOT_TOKEN_2="xxx"
export DD_BOT_SECRET_2="xxx"

...

```

当然, 我也想到其他解决方案, 比如为每一个账号创建一个容器...  但账号一多, 容器占用的系统资源也会随之上升....

**Comment by Mashiro2000** [comment]
这个功能不错，我也想要

**Comment by lan-tianxiang** [comment]
的确，我开始着手写写😊&nbsp;

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："阿航 ***@***.***&gt;;
发送时间：2021年6月2日(星期三) 下午4:15
收件人："lan-tianxiang/jd_shell" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/jd_shell] 请问能否按账号分别进行通知呢 (#97)
-----------------------------------

 

 
想要增加什么样的功能或者哪里存在不足之处呢？
 
目前的通知是N个账号都通过一个渠道进行通知, 当账号多的时候, 大家会很难找到自己账号的信息.
 
能否添加功能, 使每个cookie对应自己的通知(拿钉钉通知举例), 如:
 # 账号1 Cookie1=xxxxx # 钉钉通知 export DD_BOT_TOKEN_1="xxx" export DD_BOT_SECRET_1="xxx" # 账号二 Cookie2=xxxxx # 钉钉通知 export DD_BOT_TOKEN_2="xxx" export DD_BOT_SECRET_2="xxx" ...
 
当然, 我也想到其他解决方案, 比如为每一个账号创建一个容器...  但账号一多, 容器占用的系统资源也会随之上升....

**Comment by HarrisonQi** [comment]
感谢大佬, nb!

**Comment by qingcheng123** [comment]
请问推送为啥不行了，config写了key和编码
push+发送一对多通知消息失败：用户信息状态不合法

发送通知调用API失败！！

HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/root/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1623320679763,
    socket: 1623320679764,
    lookup: 1623320679764,
    connect: 1623320679785,
    secureConnect: 1623320679832,
    upload: 1623320679833,
    response: 1623320679879,
    end: 1623320679880,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 21,
      tls: 47,
      request: 1,
      firstByte: 46,
      download: 1,
      total: 117
    }
  }
}
您未提供Bark的APP推送BARK_PUSH，取消

**Comment by zqh2333** [comment]
弄好了么，非常需要这个功能
